### ISSUE TITLE
Developer id error

### ISSUE THREAD

**Issue by jerry-619** [ameliakiara/Lavalink-Music-Bot#4]
![IMG_20220129_181937](https://user-images.githubusercontent.com/97156677/151661666-0bf91a06-f2ea-4eea-a86d-15ceb7f85b79.jpg)

**Comment by jerry-619** [comment]
Help me how to fix this

**Comment by ameliakiara** [comment]
you should use ["Discord ID"]

**Comment by jerry-619** [comment]
![IMG_20220129_182227](https://user-images.githubusercontent.com/97156677/151661730-ccf0bd49-8df4-496d-a972-7728e56beaf4.jpg)
Already used

**Comment by ameliakiara** [comment]
don't use `space` 

DEVELOPERS=["discord id"]

**Comment by jerry-619** [comment]
![Screenshot_2022-01-29-18-32-53-102_com android chrome](https://user-images.githubusercontent.com/97156677/151662069-0e6ad18d-6a46-415e-bdc1-34b4b4f18967.jpg)
Now How to fix this :(

**Comment by ameliakiara** [comment]
have no idea about that, you can join to railway discord server and ask for help

**Comment by jerry-619** [comment]
Can you add repl hosting instead of railway
